name: "Nightly Build & Test"

on:
  schedule:
    - cron: "0 0 * * *"  # Runs nightly at midnight UTC
  workflow_dispatch:

jobs:
  build-push-test:
    runs-on: ubuntu-latest

    # Make sure your AWS credentials are set in environment variables here
    # (We also set AWS keys from GitHub secrets)
    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 120717612929
      
      # The next three lines assume you have these secrets in GitHub:
      # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      ECR_REPO_BACKEND: my-app-backend
      ECR_REPO_FRONTEND: my-app-frontend
      IMAGE_TAG: latest

    steps:
      # 1) Checkout your application code (Dockerfiles, docker-compose.test.yml, etc.)
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          repository: Sufiyan11919/crud-react-node-mySQL-go
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2) Configure AWS Credentials on the GitHub Actions runner
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3) Log in to Amazon ECR (to push newly built images)
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS \
            --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # 4) Build & Push the Backend image
      - name: Build Backend
        run: |
          cd backend
          docker build -t $ECR_REPO_BACKEND:$IMAGE_TAG .
          docker tag $ECR_REPO_BACKEND:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_BACKEND:$IMAGE_TAG

      - name: Push Backend
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_BACKEND:$IMAGE_TAG

      # 5) Build & Push the Frontend image
      - name: Build Frontend
        run: |
          cd frontend
          docker build -t $ECR_REPO_FRONTEND:$IMAGE_TAG .
          docker tag $ECR_REPO_FRONTEND:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_FRONTEND:$IMAGE_TAG

      - name: Push Frontend
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_FRONTEND:$IMAGE_TAG

      # 6) Launch an EC2 instance (key pair "myTempKeyPair"), injecting AWS creds in user data
      - name: Launch EC2
        id: launch_ec2
        run: |
          AMI_ID="ami-09940406aa41815f0"
          INSTANCE_TYPE="t2.micro"
          SECURITY_GROUP_ID="sg-0bb71744d70b0efab"
          KEY_PAIR_NAME="myTempKeyPair"

          USER_DATA="#!/bin/bash
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
          export AWS_REGION=${AWS_REGION}

          # Log in to ECR right away on instance boot:
          aws ecr get-login-password --region \$AWS_REGION \
            | docker login --username AWS \
            --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.\$AWS_REGION.amazonaws.com
          "

          CREATE_OUTPUT=$(aws ec2 run-instances \
            --image-id "$AMI_ID" \
            --instance-type "$INSTANCE_TYPE" \
            --key-name "$KEY_PAIR_NAME" \
            --security-group-ids "$SECURITY_GROUP_ID" \
            --count 1 \
            --region $AWS_REGION \
            --user-data "$USER_DATA")

          INSTANCE_ID=$(echo "$CREATE_OUTPUT" | jq -r '.Instances[0].InstanceId')
          echo "Instance ID: $INSTANCE_ID"

          aws ec2 wait instance-running --instance-ids "$INSTANCE_ID" --region $AWS_REGION
          echo "Instance $INSTANCE_ID is now running."

          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text \
            --region $AWS_REGION)
          echo "Public IP: $PUBLIC_IP"

          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      # 7) Write the SSH private key from GitHub Secrets to ec2-key.pem
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem

      - name: Wait for SSH
        run: sleep 60

      # 8) SSH into the ephemeral EC2, clone the repo, pull images from ECR, run them
      - name: Deploy & Test
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ steps.launch_ec2.outputs.public_ip }}
          username: ec2-user
          key: |
            ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            # Clone your repo to get docker-compose.test.yml
            git clone https://github.com/Sufiyan11919/crud-react-node-mySQL-go.git app
            cd app

            # If you didn't log in to ECR in user data, do it here:
            echo "Logging into ECR on ephemeral EC2..."
            aws ecr get-login-password --region $AWS_REGION \
              | docker login --username AWS \
              --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

            echo "Pulling images from ECR..."
            docker-compose -f docker-compose.test.yml pull

            echo "Starting ephemeral environment..."
            docker-compose -f docker-compose.test.yml up -d

      # 9) Simple Smoke Test using cURL
      - name: Smoke Test with cURL
        run: |
          set -e
          IP="${{ steps.launch_ec2.outputs.public_ip }}"
          echo "Waiting 20s for containers to come up..."
          sleep 20

          echo "POST a new book..."
          curl -X POST -H "Content-Type: application/json" \
            -d '{"title":"Nightly Book","description":"From GitHub Actions","price":10.50,"cover":"https://via.placeholder.com/150"}' \
            http://$IP:8800/books

          echo "GET all books..."
          curl http://$IP:8800/books

      # 10) Remove ECR images if tests fail
      - name: Remove ECR Images on Failure
        if: failure()
        run: |
          echo "Tests failed. Removing images from ECR..."
          aws ecr batch-delete-image --repository-name $ECR_REPO_BACKEND --image-ids imageTag=$IMAGE_TAG --region $AWS_REGION
          aws ecr batch-delete-image --repository-name $ECR_REPO_FRONTEND --image-ids imageTag=$IMAGE_TAG --region $AWS_REGION

      # 11) Terminate ephemeral EC2
      - name: Terminate EC2
        if: always()
        run: |
          INSTANCE_ID="${{ steps.launch_ec2.outputs.instance_id }}"
          if [ -n "$INSTANCE_ID" ]; then
            echo "Terminating EC2 instance $INSTANCE_ID..."
            aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" --region $AWS_REGION
            aws ec2 wait instance-terminated --instance-ids "$INSTANCE_ID" --region $AWS_REGION
            echo "Instance terminated."
          fi
