name: "Nightly Build & Test"

on:
  schedule:
    - cron: "0 0 * * *"  # 12AM UTC
  workflow_dispatch:

jobs:
  build-push-test:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 120717612929
      ECR_REPO_BACKEND: my-app-backend
      ECR_REPO_FRONTEND: my-app-frontend
      IMAGE_TAG: latest

    steps:
      # 1) Checkout source code (so we can build images if tests pass)
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          repository: Sufiyan11919/crud-react-node-mySQL-go
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2) Configure AWS Credentials (needed to call EC2 APIs)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3) Launch ephemeral EC2 (Amazon Linux 2, no ECR login in user data)
      - name: Launch EC2
        id: launch_ec2
        run: |
          # Create key pair
          KEY_PAIR_NAME="github-actions-key-$$"
          aws ec2 create-key-pair --key-name "$KEY_PAIR_NAME" --query "KeyMaterial" --output text > ec2-key.pem
          chmod 400 ec2-key.pem

          # Official Amazon Linux 2 AMI in us-east-1
          AMI_ID="ami-09e67e426f25ce0d7"
          INSTANCE_TYPE="t2.micro"
          SECURITY_GROUP_ID="sg-0bb71744d70b0efab"

          # user_data installs Docker & Git, but does NOT login to ECR
          USER_DATA="#!/bin/bash
          yum update -y
          yum install -y docker git
          systemctl enable docker
          service docker start
          "

          CREATE_OUTPUT=$(aws ec2 run-instances \
            --image-id "$AMI_ID" \
            --instance-type "$INSTANCE_TYPE" \
            --key-name "$KEY_PAIR_NAME" \
            --user-data "$USER_DATA" \
            --security-group-ids "$SECURITY_GROUP_ID" \
            --count 1)

          INSTANCE_ID=$(echo "$CREATE_OUTPUT" | jq -r '.Instances[0].InstanceId')
          echo "Instance ID: $INSTANCE_ID"

          aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
          echo "Instance $INSTANCE_ID is now running."

          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" \
            --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "Public IP: $PUBLIC_IP"

          # Expose outputs to other steps
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
          echo "key_pair_name=$KEY_PAIR_NAME" >> $GITHUB_OUTPUT

      # 4) Wait for SSH
      - name: Wait for SSH
        run: sleep 60

      # 5) Read out the private key so we can SSH
      - name: Read EC2 Key
        id: read_key
        run: |
          echo "private_key<<EOF" >> $GITHUB_OUTPUT
          cat ec2-key.pem >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 6) SSH: Clone repo & run Docker Compose test
      - name: Run Test on Temp EC2
        uses: appleboy/ssh-action@v0.1.8
        id: test_on_ec2
        with:
          host: ${{ steps.launch_ec2.outputs.public_ip }}
          username: ec2-user
          key: ${{ steps.read_key.outputs.private_key }}
          script: |
            set -e
            echo "Cloning repo..."
            git clone https://github.com/Sufiyan11919/crud-react-node-mySQL-go.git app
            cd app

            echo "Starting containers via docker-compose.test.yml..."
            docker-compose -f docker-compose.test.yml build
            docker-compose -f docker-compose.test.yml up -d

            echo "Containers started. Checking logs & status..."
            docker-compose -f docker-compose.test.yml ps
            docker-compose -f docker-compose.test.yml logs backend

      # 7) Smoke Test from GH runner with cURL
      - name: Smoke Test with cURL
        id: smoke_test
        run: |
          set -e
          IP="${{ steps.launch_ec2.outputs.public_ip }}"
          echo "Waiting 30s for app to fully initialize..."
          sleep 30

          echo "POST a new book..."
          curl -X POST -H "Content-Type: application/json" \
            -d '{"title":"Nightly Book","description":"From GitHub Actions","price":10.50,"cover":"https://via.placeholder.com/150"}' \
            http://$IP:8800/books

          echo "GET all books..."
          curl http://$IP:8800/books

      # 8) If tests pass, build images on GH runner and push to ECR
      - name: Log in to ECR (on GH runner)
        if: success()
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS \
            --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Backend (on GH runner)
        if: success()
        run: |
          cd backend
          docker build -t my-backend-local:latest .
          # Tag for ECR
          docker tag my-backend-local:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_BACKEND:$IMAGE_TAG

      - name: Build Frontend (on GH runner)
        if: success()
        run: |
          cd frontend
          docker build -t my-frontend-local:latest .
          # Tag for ECR
          docker tag my-frontend-local:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_FRONTEND:$IMAGE_TAG

      - name: Push Backend to ECR
        if: success()
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_BACKEND:$IMAGE_TAG

      - name: Push Frontend to ECR
        if: success()
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_FRONTEND:$IMAGE_TAG

      # 9) Terminate ephemeral EC2
      - name: Terminate EC2
        if: always()
        run: |
          INSTANCE_ID="${{ steps.launch_ec2.outputs.instance_id }}"
          KEY_PAIR_NAME="${{ steps.launch_ec2.outputs.key_pair_name }}"
          if [ -n "$INSTANCE_ID" ]; then
            echo "Terminating EC2 instance $INSTANCE_ID..."
            aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
            aws ec2 wait instance-terminated --instance-ids "$INSTANCE_ID"
            echo "Instance terminated."
          fi
          echo "Deleting temporary key pair..."
          aws ec2 delete-key-pair --key-name "$KEY_PAIR_NAME"
