name: "Test Secret Injection"

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Masked Secret
        run: echo "MY_SECRET: ${MY_SECRET:0:4}********"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
